- cmd/wait-for-github/pr.go
We're watching for a PR, it's only ever going to be one (new head) commit. Not much sense outputting a list. This makes consuming the result a bit easier.
> pr: Don't output a list

- README.md
- cmd/wait-for-github/ci.go
- internal/github/github.go
Sometimes status checks are not reported immediately, for example in the case where a webhook request is sent and the receiver is responsible for deciding whether to create it. Just waiting for the overall CI status does not necessarily guarantee that all eventual checks have been created and have reported their result.
Add a new commandline flag to wait for a specific check to have a result. This flag can be given multiple times to wait for multiple statuses.
There are two types of checks in the world of GitHub: checks and statuses. We check for both so it doesn't matter when you give the flag which kind of check you're looking for.
> ci: Add ability to wait for specific checks

- README.md
- cmd/wait-for-github/pr.go
- cmd/wait-for-github/root.go
- internal/github/github.go
This attribute is important for my use-case because I need to reference the time before a PR was merged.
Also, the `commit-info-file` flag was missing from the docs, so I added it in a drive-by refactor.
> Capture timestamp when PR was merged

- internal/github/github.go
I was overwriting the Transport when trying to use a cache. It meant that the token wasn't being used for requests, which is no good.
Closes: #26
> github: Fix HTTP client when using token

- README.md
- action.yml
- cmd/wait-for-github/ci.go
Also add an environment variable for the `ci --check` parameter. This lets the action pass in multiple comma-separated checks to be waited on individually. The `urfave/cli` library we are using splits this automatically.
> Add an action to wait for CI checks

- .github/workflows/golangci-lint.yml
- cmd/wait-for-github/pr.go
- go.mod
Just using the default settings. I went for the action rather than adding to the Drone pipeline because then [you get annotations on PRs pointing to the code](https://github.com/golangci/golangci-lint-action). Don't feel that strongly about that though, so lmk what you think.
I also fixed the problem which it found.
> Add golangci-lint action

- .drone.yml
- jsonnet/drone.jsonnet
We don't need them there, we're only pulling from public repos. They're only needed to push when PRs are merged to main.
The only reason to maybe have wanted them would be to get the higher rate limits it gives. Hopefully that's not needed.
> drone: Don't mount docker credentials for PRs

- cmd/wait-for-github/ci.go
- cmd/wait-for-github/config.go
- cmd/wait-for-github/main.go
- cmd/wait-for-github/pr.go
- cmd/wait-for-github/root.go
- internal/github/github.go
- internal/github/github_test.go
- internal/utils/utils.go
- internal/utils/utils_test.go
This is part of a _PR stack_:
* #57 <- you are here
* #58  + #59
* #60
I started to add a new feature in #60, and wanted to add tests for it. But it turned out to be quite difficult due to the global state we have in the project, and the way the commands are constructed.
So here's a pre-PR with quite a bit of reorganisation of the code. I'll follow up with tests for the CI and PR subcommands, and then the new feature™.
Have tried to split the work into logical commits with each commit having a decent message, but if this is still too big to review then I can push each of those as separate PRs, just let me know. :+1:
> Refactor for testability

- cmd/wait-for-github/ci.go
- cmd/wait-for-github/ci_test.go
This is part of a _PR stack_:
* #57
* #58 <- you are here + #62
* #61
> Add tests for the CI subcommand

- cmd/wait-for-github/pr.go
- cmd/wait-for-github/pr_test.go
- internal/github/github.go
- internal/github/github_test.go
This is part of a _PR stack_:
* #57
* #58  + #59
* #61 <- you are here
In this case the PR will probably not be merged, but we can fail waiting
for it if its combined status is failed.
I'm undecided on whether we should unconditionally do this, add a flag, and/or allow passing named checks. In here now I've gone for just doing it unconditionally, maybe we can see how that goes.
> pr: Fail when the CI status fails

- README.md
- action.yml
- cmd/wait-for-github/ci.go
- cmd/wait-for-github/ci_test.go
- cmd/wait-for-github/pr.go
This allows us to check the status the status of the HEAD of a PR by just knowing the PR number.
> Add support for using a PR URL instead of commit SHA

- .editorconfig
- .github/workflows/build.yml
- .github/workflows/golangci-lint.yml
- action.yml
- go.mod
See the individual commits - some cleanups.
The main one I _want_ here is the go 1.22 bump, because CodeQL is warning about the `toolchain` not being there, and I'm not sure if that is preventing it from running.
> Go 1.22 & cleanups

- cmd/wait-for-github/ci.go
- cmd/wait-for-github/ci_test.go
Recently while debugging a Tempo deployment issue I was confused by the error message "CI failed" in the logs. It seems obvious in retrospect, but it did not occur to me that Tempo's CI had failed or where it had failed.
This PR extends the error message with a link to the commit that is currently failing to help speed up diagnosis of similar issues and reduce confusion.
> Improve wait-for-ci failure message

- go.mod
[CodeQL is still telling us that this file is wrong][warning]. Upon closer reading of [the docs on the file format][docs], `go 1.22` is not valid since `1.22` was not a release of Go. We need to specify a release which existed here, and not a minor version of the language which was what I thought this was before.
Fix it to `go 1.22.2`. Since that is equal to what we had in `toolchain`, the `toolchain` line is no longer needed: delete it.
[docs]: https://tip.golang.org/doc/toolchain#version
[warning]: https://github.com/grafana/wait-for-github/actions/runs/8875865988/job/24366210697
> go.mod: Fix `go` format

- go.mod
- internal/github/github.go
- internal/github/github_test.go
When there are no statuses on a reference, [GitHub will report the combined status as `pending`][docs]. This is because status checks can be added at any time, and so it's not possible to know if the remote end just hasn't started its check yet, so they play it safe.
That doesn't work for us, though - we need to exit in a finite amount of time. Currently we don't. With this change, we'll check if there were any statuses reported if the combined status is `pending`. If there are, then we really are pending. If there aren't, we will wait for 5 seconds, look again and if it's still empty then we will say the commit passed CI. If something has changed then we return "Unknown" and we'll get called again in due course to see what happened and report the right thing next time.
Here's our real …
> ci: Don't want forever when there are no statuses

- cmd/wait-for-github/ci_test.go
- go.mod
- internal/github/github.go
- internal/github/github_test.go
We've come across some cases now where there are over 100 statuses. In that case, as 21247305c86ad1a97fa67b9db4473ef478db4898 shows, we don't find what we're looking for.
The `go-github` package fully supports pagination, we simply weren't using it. Here we update to use it and fix the issue.
I pushed 21247305c86ad1a97fa67b9db4473ef478db4898 first. See CI on that commit for the failure, and then we can see how it passes with the latest commit here.
We also had a real failure internally that I verified is now fixed, but I can't share it here I'm afraid, as it's a private repo.
> github: Process all pages of results

- action.yml
We don't gain very much by using a Docker container action. Builds are slow, and we just learned internally at Grafana Labs that Actions runners skip the Docker daemon config (which we use for a proxy) when building Docker container actions.
A composite one should work just fine.
> chore(action): switch to a composite action

- go.mod
- go.sum
- internal/github/github.go
- internal/github/github_test.go
This API allows us to get both checks and statuses in one call, and gives us an overall status of all the CI checks. This means we can get rid of the `getCIChecksResult` and `getCombinedStatus` functions. Additionally, `GetCIStatus` will now individually log any failed checks or statuses from the query.
Here are some results from testing:
- Query on commit with statuses & checks
```
DEBU[2025-01-14 16:34:32] Debug logging enabled                        
DEBU[2025-01-14 16:34:32] Will use GitHub token for authentication     
DEBU[2025-01-14 16:34:32] Using token starting with ghp_8kXW80...      
DEBU[2025-01-14 16:34:32] Using GitHub token for authentication        
INFO[2025-01-14 16:34:32] Checking CI status on dblinkhorn/wait-for-github-graphql-test@23c27195d5172ddf9a4bef27243370e4285481 …
```
> feat(ci): modify GetCIStatus to utilize GitHub GraphQL API

- README.md
With 7151b52a53becb98caf329b3c4e9d6af38abb521 the permissions required changed and our internal runs stopped working until I added `contents:read` to our app.
It made me realise that we hadn't documented which permissions you need to use `wait-for-github`. So here we are!
Closes: #71
> docs: document permissions required for token

- README.md
In 0239f23b0729b1ebf2d76786e39a206df2618684 we started retrieving counts and names of workflows which ran in the target repository. I wasn't expecting it to require any more permissions but it seems like this does need `actions:read`. This commit documents that new requirement.
> docs(permissions): document `actions:read` permission required for counts

- cmd/wait-for-github/ci.go
- cmd/wait-for-github/ci_test.go
- cmd/wait-for-github/pr.go
- cmd/wait-for-github/pr_test.go
- internal/utils/utils.go
- internal/utils/utils_test.go
- removed `recheckInterval` from the `Check` interface
- updated all `Check` implementations to match the new signature
- removed all downstream references to `recheckInterval` in logs
- moved the 'Rechecking in...' log statement to `RunUntilCancelledOrTimeout`
The downside of this change is that we will now have two separate log lines. One from `RunUntilCancelledOrTimeout` (1st line) and one from other functions that previously logged `recheckInterval` directly.
```
PR is not closed yet
Rechecking in 15s...
```
If this isn't what we want then we could pass a logger function around, but that doesn't seem much different than just passing `recheckInterval` like we currently do.
> fix(ci): remove recheckInterval from Check interface

- .github/workflows/codeql.yml
It appears that the protections for the main branch prevent merging PRs that come from forks where CodeQL has not run on the commit. However, setting up CodeQL on the fork would also have that file addition be in the code PR to the origin here. This change adds the default advanced config for CodeQL in the hopes that the on:pull_request action enables these CodeQL checks on the PR itself.
> feat: add advanced codeql workflow

- README.md
- action.yml
- cmd/wait-for-github/ci.go
- cmd/wait-for-github/ci_test.go
- cmd/wait-for-github/pr.go
- cmd/wait-for-github/pr_test.go
- internal/github/github.go
- internal/github/github_test.go
Closes #80 
If you want to ignore a single check in your CI today you have to specify all check names _except_ the one you want to ignore in the `--check=<check>` flags. This can create a burden to ensure your arguments stay up to date with any CI check changes you make.
This change adds a different option to specify `--exclude=<check>`. So if you add or change other checks, wait-for-github still continues to work as expected. This argument is less strict than `--check=<check>` meaning if you specify checks specifically, there should be no need to exclude any of the checks, so the argument is ignored in that case.
> feat: add  option to ignore specific checks

- .github/workflows/build.yml
- .github/workflows/codeql.yml
- .github/workflows/lint.yml
We do clone with `contents: read` permission, but cloning will still [put the github token into `.git/config`][artipacked]. Even though it's low risk in this repository, we might as well not do it. We don't need to persist the credentials as we don't use `git` again after we do the initial checkout.
[artipacked]: https://woodruffw.github.io/zizmor/audits/#artipacked
> ci: don't persist github credentials

- .github/workflows/build.yml
- .github/workflows/codeql.yml
- .github/workflows/release.yml
- Dockerfile
I just ran [zizmor] on the repo. This fixes the lints it found. There's a small improvement to build efficiency too: download the Go dependencies separately. This means they get their own layer in the container build, which can be reused if the deps don't change.
[zizmor]: https://woodruffw.github.io/zizmor/
> ci: fix lints picked up by zizmor

- .github/workflows/release.yml
Release-please needs to operate in the checkout to have access to the configuration and the docker job needs access to the output of release-please.
> ci: fix release-please output and context

- internal/github/errors.go
- internal/github/github.go
- internal/github/github_test.go
Add GitHub API response error handling:
- Rate limit errors with reset time reporting
- Abuse detection errors with retry info
- `AcceptedError` (202) responses for pending operations
- General API errors with status codes
- Fix handling of `CIStatusPending` state when GitHub returns `AcceptedError`
Closes #23.
> ci: utilize github.CheckResponse to handle API errors

- Dockerfile
- cmd/wait-for-github/ci_list.go
In 7eecb18919b5d1fc98620cbe20d9b2dfc1f3fa8a we introduced support for title casing CI statuses in our output, using the [`text/transform`] package.
This was done using a `caser` instanced, which was defined as a shared (global) `ANSITransformer` instance.
Unfortunately doing this with a global variable opens us up to a race condition which we are triggering with the testsuite. When tests run with `t.Parallel()`, as we do, multiple goroutines simultaneously call `transform.String(caser, ...)` on the single instance. Each modifies the transformer's internal state concurrently, causing data races which result in incorrect results and, in the case of the testsuite, failing tests.
The race detector output showed concurrent read/write access to the same memory location in …
> fix: don't share non-thread-safe ANSITransformer instance

- cmd/wait-for-github/root.go
- internal/logging/logging.go
The `--log-level` flag was being completely ignored - even when explicitly provided on the command line, the application would always use the default log level instead of the selected level.
The issue was occurring because `cmd.Generic("log-level")` was returning `nil` in the `Before` hook, even when the flag was provided. This is due to differences in parsing of root / command-specific flags in `urfave/cli` v3.
We've fixed this by implementing a flag action (function that executes when the flag is set), which configures the logger with the user-specified level. This required implementing `flag.Value` rather than `TextUnmarshaler` - again a requirement of `urfave/cli` v3.
The phasing of when things are executed is slightly different now. We have:
1. `Before` hook: initialises the config …
> fix(cli): fix `--log-level` flag being ignored
